minimal blk virtio driver

diff --git a/tools/packrootfs b/tools/packrootfs
--- a/tools/packrootfs
+++ b/tools/packrootfs
@@ -1,7 +1,7 @@
 #!/bin/bash
 
 if [ $# -lt 2 ]; then
-    echo "Usage: $0 <rootfs> <tmpdir> [-o output_rootfs] [--startup files...] [--home files...] [--etc files...]"
+    echo "Usage: $0 <rootfs> <tmpdir> [-o output_rootfs] [--init init_file] [--startup files...] [--home files...] [--etc files...]"
     exit 1
 fi
 
@@ -11,6 +11,7 @@ startup_files=()
 home_files=()
 etc_files=()
 output_rootfs=""
+init_file=""
 
 shift 2
 while [[ $# -gt 0 ]]; do
@@ -35,6 +36,16 @@ while [[ $# -gt 0 ]]; do
                 etc_files+=("$1")
                 shift
             done
+            ;;
+        --init)
+            shift
+            if [[ $# -gt 0 ]]; then
+                init_file=$1
+                shift
+            else
+                echo "Error: --init option requires an argument."
+                exit 1
+            fi
             ;;
         -o)
             shift
@@ -61,6 +72,11 @@ rm -rf "$tmpdir"
 mkdir -p "$tmpdir"
 mkdir -p "$tmpdir/root"
 mkdir -p "$tmpdir/etc/init.d"
+
+if [[ "$init_file" != "" ]]; then
+    cp -- "$init_file" "$tmpdir/init"
+    chmod +x "$tmpdir/init"
+fi
 
 # Copy home files to /root
 for file in "${home_files[@]}"; do
